### PR TITLE
Fixed lambda icon

### PR DESCRIPTION
**Pull request by sei40kr**
Fixed an issue that the lambda icon won't appear on some environments.

### CODE REVIEW

**Comment by halfo** [comment]
Hey, sorry for this long late reply. And thanks for the pull request! Would you like to share on which platforms did you test this change? The main challenge that one thing may work in one terminal, os or zsh-package-manger but in others, it won't. I also would need to ask other peoples help to very if it is working or not.

**Comment by sei40kr** [comment]
I tried only on Ubuntu + zplug environment. At first, the icon wouldn't appear.

**Reason**
A variable `PROMPT` is single-quoted, so `${LAMBDA}` gets evaluated on rendering prompt.
But a variable `LAMBDA` is a local variable, so it can't be referred by the prompt renderer on some environments.

**Solutions**
* Embed the content of `${LAMBDA}` into `PROMPT`. (I chose this)
* Make `LAMBDA` global.

**Comment by Ma27** [comment]
I'll try it on my setup tonight...

**Comment by halfo** [comment]
@Ma27 Thanks! It would be really helpful!!

**Comment by Ma27** [comment]
I finally found some time to verify the change locally. It still works (additional `git` information is displayed as well), however I experienced a minor regression: there are no empty lines before/after one prompt, so my `stdout` looks like this ATM:

```
λ ma27 [~] → 
λ ma27 [~] → 
λ ma27 [~] → 
λ ma27 [~] → 
λ ma27 [~] → 
λ ma27 [~] → 
λ ma27 [~] → 
λ ma27 [~] → 
λ ma27 [~] → 
λ ma27 [~] → 
λ ma27 [~] → 
λ ma27 [~] → nxc
λ ma27 [~/Projects/nixos-config] at  master !
→                                                                                                            [df6cd6c]
λ ma27 [~/Projects/nixos-config] at  master !
→                                                                                                            [df6cd6c]
λ ma27 [~/Projects/nixos-config] at  master !
→                                                                                                            [df6cd6c]
```

This is a behavior change I'm not happy with tbh.

###### Additional information

I'm using `termite` in version 12 on NixOS `17.09pre110094.1add3519df (Hummingbird)`.

The expression I used to override this package looked like this:

``` nix
{ ... }:
{
  nixpkgs.config.packageOverrides = super: let pkgs = super.pkgs; in {
    lambda-mod-zsh-theme = super.lambda-mod-zsh-theme.overrideAttrs (a: {
        name = "lambda-mod-custom";
        src = pkgs.fetchFromGitHub {
          owner = "sei40kr";
          repo = "lambda-mod-zsh-theme";
          rev = "3e39fc7aff0bfea25a2b8894a5cdee3cb6425586";
          sha256 = "0n59vzpfwjhqnx5l73zsz7rvvdgh3rwfri2n2w0ynb6nzdjni2h0";
       };
    });
  };
}
```

Just ping me if you need any further information :-)

**Comment by sei40kr** [comment]
@Ma27 Sorry, I didn't noticed.
I've also fixed the regression issue and confirmed it's fixed on my environment.
Can you update the cache of my repo and retry a test? Thank you for your corporation.

**Comment by Ma27** [comment]
looks good now, so :+1: from my side :-)

**Comment by halfo** [comment]
Cool! I'll test this on my machine (tonight إن شاء الله‎‎) and let you guys know about the status.

**Comment by halfo** [comment]
Looks good from my side. Cheers!

**Pull request merged**
